services:
    _defaults:
        autowire: true
        autoconfigure: true

    OHMedia\TestimonialBundle\:
        resource: '../src/'
        exclude:
            - '../src/Entity/'
            - '../src/OHMediaTestimonialBundle.php'
